### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by PWAAAA** [lucidrains/big-sleep#110]
Using "imagine" or "dream" commands results in this error message: 

C:\Users\natej>
C:\Users\natej>imagine
Traceback (most recent call last):
  File "c:\users\natej\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\natej\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\natej\AppData\Local\Programs\Python\Python38\Scripts\imagine.exe\__main__.py", line 4, in <module>
  File "c:\users\natej\appdata\local\programs\python\python38\lib\site-packages\deep_daze\__init__.py", line 1, in <module>
    from deep_daze.deep_daze import DeepDaze, Imagine
  File "c:\users\natej\appdata\local\programs\python\python38\lib\site-packages\deep_daze\deep_daze.py", line 8, in <module>
    import torch
  File "c:\users\natej\appdata\local\programs\python\python38\lib\site-packages\torch\__init__.py", line 135, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "c:\users\natej\appdata\local\programs\python\python38\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.

I was previously having a CUDA error so i followed this: https://github.com/lucidrains/deep-daze/issues/78 which got rid of the CUDA error message but now I have this

**Comment by PWAAAA** [comment]
does anyone know what's going on? I can't find anything online about this and its extremely confusing
