### ISSUE TITLE
RuntimeError: Model has been downloaded but the SHA256 checksum does not not match

### ISSUE THREAD

**Issue by ThatOneCalculator** [lucidrains/big-sleep#124]
Python: 3.8
OS: Linux
```
$ dream 'a flower in an endless field'
100%|███████████████████████████████████████| 354M/354M [01:04<00:00, 5.46MiB/s]
Traceback (most recent call last):
  File "/home/kainoa/.local/bin/dream", line 5, in <module>
    from big_sleep.cli import main
  File "/home/kainoa/.local/lib/python3.8/site-packages/big_sleep/__init__.py", line 1, in <module>
    from big_sleep.big_sleep import BigSleep, Imagine
  File "/home/kainoa/.local/lib/python3.8/site-packages/big_sleep/big_sleep.py", line 135, in <module>
    perceptor, normalize_image = load('ViT-B/32', jit = False)
  File "/home/kainoa/.local/lib/python3.8/site-packages/big_sleep/clip.py", line 93, in load
    model_path = _download(_MODELS[name])
  File "/home/kainoa/.local/lib/python3.8/site-packages/big_sleep/clip.py", line 54, in _download
    raise RuntimeError(f"Model has been downloaded but the SHA256 checksum does not not match")
RuntimeError: Model has been downloaded but the SHA256 checksum does not not match
```

**Comment by RuihanGao** [comment]
I have the same problem. How is it solved?

**Comment by Osub** [comment]
I have the same problem. How is it solved?

**Comment by ThatOneCalculator** [comment]
Use python 3.7.9 instead
