### ISSUE TITLE
Does it work on mac ?

### ISSUE THREAD

**Issue by NtnmrnNtnmrn** [lucidrains/big-sleep#135]
Hello
Newbie here. I'm on Mac M1
Installation worked with "pip install big-sleep"
But then when I try "dream..." it says "command not found"
Does anyone know why and how to make it work ?
Thanks a lot

**Comment by Ednaordinary** [comment]
Did you do
```pip install big-sleep
python3
import big-sleep.Imagine as dream
dream(text = "text")
```

Or just
```pip install big-sleep
dream(text = "text")
```
?
The dream command is not available directly from the shell, you have to enter python and import big-sleep. also, this may not be an issue to you, but if it says no module called big-sleep you may want to `exit()` and use `pip3` or `python3 -m pip` instead of `pip`, if you have multiple versions of python installed. Then re-enter python3 and try again

**Comment by NtnmrnNtnmrn** [comment]
Thank you for your answer.

When I enter python3 and write "import big-sleep.Imagine as dream"
It says : 

```
  File "<stdin>", line 1
    import big-sleep.Imagine as dream
              ^
SyntaxError: invalid syntax 
```

This doesn't get better with pip3 or python3 -m pip instead of pip.

**Comment by Ednaordinary** [comment]
Sorry, typo. try this instead
`big_sleep.Imagine as dream`

**Comment by NtnmrnNtnmrn** [comment]
Thanks ! but I get the same

` File "<stdin>", line 1
    big_sleep.Imagine as dream
                      ^
SyntaxError: invalid syntax`

EDIT : ok it worked with "import big_sleep.Imagine as dream"

I get : 

`>>> import big_sleep.Imagine as dream
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/.../Downloads/big-sleep-main/big_sleep/__init__.py", line 1, in <module>
    from big_sleep.big_sleep import BigSleep, Imagine
  File "/Users/.../Downloads/big-sleep-main/big_sleep/big_sleep.py", line 26, in <module>
    assert torch.cuda.is_available(), 'CUDA must be available in order to use Big Sleep'
AssertionError: CUDA must be available in order to use Big Sleep`

**Comment by Ednaordinary** [comment]
If you look at issue #131, it looks like big sleep won't work without cuda. To answer your original question, it won't work on most of all macs (I'm not sure if older mac's with Nvidia GPUs would work, but probably not)

**Comment by NtnmrnNtnmrn** [comment]
Ok thanks! :)
