### ISSUE TITLE
ValueError: Expected tensor to be a tensor image of size (C, H, W). Got tensor.size() = torch.Size([128, 3, 224, 224])

### ISSUE THREAD

**Issue by Danscap** [lucidrains/big-sleep#29]
I got this very specific error that is preventing the command line tool (dream 'query') from running with every query I have tried. I am not sure if we are supposed to input dimensions, but the Read Me did not specify anything.

This is from running the pip install command.

Is it possible this is a torch version issue?

According to the command 'print(torch.__version__) my version is 1.7.1+cu110 .

Please advise!

**Comment by lucidrains** [comment]
@Danscap hmm, that's really weird, what system are you on?

**Comment by Danscap** [comment]
@lucidrains I am on windows 10 home. Is that the issue?

Could the issue instead be that the version of this software installed from pip is outdated?

**Comment by Danscap** [comment]
@lucidrains here is the full output of the error:

___________________________________________________________
Imagining "a slice of ham with a human mouth" from the depths of my weights...
iteration:   0%|                                                                              | 0/1050 [00:00<?, ?it/s]
epochs:   0%|                                                                                   | 0/20 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "c:\users\jorge\appdata\local\programs\python\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\jorge\appdata\local\programs\python\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Jorge\AppData\Local\Programs\Python\Python38\Scripts\dream.exe\__main__.py", line 7, in <module>
  File "c:\users\jorge\appdata\local\programs\python\python38\lib\site-packages\big_sleep\cli.py", line 42, in main
    fire.Fire(train)
  File "c:\users\jorge\appdata\local\programs\python\python38\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "c:\users\jorge\appdata\local\programs\python\python38\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "c:\users\jorge\appdata\local\programs\python\python38\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "c:\users\jorge\appdata\local\programs\python\python38\lib\site-packages\big_sleep\cli.py", line 39, in train
    imagine()
  File "c:\users\jorge\appdata\local\programs\python\python38\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "c:\users\jorge\appdata\local\programs\python\python38\lib\site-packages\big_sleep\big_sleep.py", line 237, in forward
    loss = self.train_step(epoch, i)
  File "c:\users\jorge\appdata\local\programs\python\python38\lib\site-packages\big_sleep\big_sleep.py", line 207, in train_step
    losses = self.model(self.encoded_text)
  File "c:\users\jorge\appdata\local\programs\python\python38\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "c:\users\jorge\appdata\local\programs\python\python38\lib\site-packages\big_sleep\big_sleep.py", line 130, in forward
    into = normalize_image(into)
  File "c:\users\jorge\appdata\local\programs\python\python38\lib\site-packages\torchvision\transforms\transforms.py", line 166, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "c:\users\jorge\appdata\local\programs\python\python38\lib\site-packages\torchvision\transforms\functional.py", line 193, in normalize
    raise ValueError('Expected tensor to be a tensor image of size (C, H, W). Got tensor.size() = '
ValueError: Expected tensor to be a tensor image of size (C, H, W). Got tensor.size() = torch.Size([128, 3, 224, 224]).



_______________________________________________________

**Comment by lucidrains** [comment]
@Danscap I just did a fresh install and it works fine

maybe it is a windows thing, but i'm not sure

**Comment by DrJKL** [comment]
@Danscap Could you try updating your pip installations? 
https://www.activestate.com/resources/quick-reads/how-to-update-all-python-packages/

**Comment by Danscap** [comment]
@DrJKL while I did have some outdated packages that were updated with the commands from the article. Trying afterwards gave the same result.

It's possible the way this code is structured, it may only work on Linux?

**Comment by DrJKL** [comment]
I've been running it exclusively on Windows 10.

**Comment by htoyryla** [comment]
> return F.normalize(tensor, self.mean, self.std, self.inplace)
> File "c:\users\jorge\appdata\local\programs\python\python38\lib\site-packages\torchvision\transforms\functional.py", line 193, in normalize
> raise ValueError('Expected tensor to be a tensor image of size (C, H, W). Got tensor.size() = '
> ValueError: Expected tensor to be a tensor image of size (C, H, W). Got tensor.size() = torch.Size([128, 3, 224, 224]).

Looks like a quite old version of torchvision is in use.

**Comment by Danscap** [comment]
@htoyryla what torchvision version do you recommend? I have 0.6.1 according to 'print(torchvision.__version__)'

**Comment by htoyryla** [comment]
I have 0.8.2. I guess 0.8.x versions are the ones to use with pytorch 1.7.x . There seems been a lot of development going on torchvision transforms. 

I am a bit baffled by the line number in your error message, though, the corresponding line in 0.6.1 should be around 290.
