### ISSUE TITLE
AssertionError: CUDA must be available in order to use Deep Daze

### ISSUE THREAD

**Issue by FlashlightET** [lucidrains/big-sleep#38]
```(bigsleep) c:\frart>python reeeeeeeeeeeeeeeeeeeeeeeeeee.py
Traceback (most recent call last):
  File "reeeeeeeeeeeeeeeeeeeeeeeeeee.py", line 1, in <module>
    from big_sleep import Imagine
  File "C:\Users\FlashlightBulbton\anaconda3\envs\bigsleep\lib\site-packages\big_sleep\__init__.py", line 1, in <module>
    from big_sleep.big_sleep import BigSleep, Imagine
  File "C:\Users\FlashlightBulbton\anaconda3\envs\bigsleep\lib\site-packages\big_sleep\big_sleep.py", line 22, in <module>
    assert torch.cuda.is_available(), 'CUDA must be available in order to use Deep Daze'
AssertionError: CUDA must be available in order to use Deep Daze

(bigsleep) c:\frart>nvidia-smi
Thu Feb 25 09:57:47 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 451.48       Driver Version: 451.48       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 166... WDDM  | 00000000:08:00.0  On |                  N/A |
| 40%   50C    P2    35W / 125W |   2038MiB /  6144MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
```
literally every other ai i use (i use a lot of them, stylegan, wav2lip, etc etc) works fine on this pc (theyre all in different conda environments)

**Comment by FlashlightET** [comment]
my main environment has an entirely different error,
```Traceback (most recent call last):
  File "C:/frart/reeeeeeeeeeeeeeeeeeeeeeeeeee.py", line 1, in <module>
    from big_sleep import Imagine
  File "C:\Users\Flashlight Bulbton\AppData\Local\Programs\Python\Python37\lib\site-packages\big_sleep\__init__.py", line 1, in <module>
    from big_sleep.big_sleep import BigSleep, Imagine
  File "C:\Users\Flashlight Bulbton\AppData\Local\Programs\Python\Python37\lib\site-packages\big_sleep\big_sleep.py", line 85, in <module>
    perceptor, preprocess = load()
  File "C:\Users\Flashlight Bulbton\AppData\Local\Programs\Python\Python37\lib\site-packages\big_sleep\clip.py", line 167, in load
    model = torch.jit.load(model_path, map_location = device).eval()
  File "C:\Users\Flashlight Bulbton\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\jit\__init__.py", line 228, in load
    cpp_module = torch._C.import_ir_module(cu, f, map_location, _extra_files)
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at ..\caffe2\serialize\inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 4, but the maximum supported version for reading is 3. Your PyTorch installation may be too old.
```

**Comment by htoyryla** [comment]
> RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at ..\caffe2\serialize\inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 4, but the maximum supported version for reading is 3. Your PyTorch installation may be too old.
> ```

Looks like your pytorch version is older and model has been stored on a newer version.

**Comment by htoyryla** [comment]
> literally every other ai i use (i use a lot of them, stylegan, wav2lip, etc etc) works fine on this pc (theyre all in different conda environments)

Check that this conda environment has cudatoolkit installed.

**Comment by LtqxWYEG** [comment]
I get the same error but I have a AMD card. I assume this is not really "easily accessible to anyone who owns **a GPU**" and that it only works with nVidia cards. I'm sad. :( There is nothing cool I can do with my card. (RX570 8GB)

**Comment by Mr-O1** [comment]
getting the same error, i installed cudatoolkit from nvidia website and I'm still getting the same error

**Comment by justinkuhn** [comment]
I get the same errror

(voice-clone) C:\Users\jtkuh\code\python\bigsleep>python start.py
Traceback (most recent call last):
  File "start.py", line 1, in <module>
    from big_sleep import Imagine
  File "C:\Users\jtkuh\.conda\envs\voice-clone\lib\site-packages\big_sleep\__init__.py", line 1, in <module>
    from big_sleep.big_sleep import BigSleep, Imagine
  File "C:\Users\jtkuh\.conda\envs\voice-clone\lib\site-packages\big_sleep\big_sleep.py", line 26, in <module>
    assert torch.cuda.is_available(), 'CUDA must be available in order to use Big Sleep'
AssertionError: CUDA must be available in order to use Big Sleep

(voice-clone) C:\Users\jtkuh\code\python\bigsleep>nvidia-smi
Thu Jul  8 22:32:01 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 466.27       Driver Version: 466.27       CUDA Version: 11.3     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   43C    P8    N/A /  N/A |    102MiB /  2048MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     12552    C+G   ...ser\Application\brave.exe    N/A      |
+-----------------------------------------------------------------------------+

**Comment by galaxyentity904** [comment]
Fix is actually quite easy

Important: big sleep only works on Nvidia gpus

So your all getting a CUDA error saying CUDA isn't available, 

Simply install CUDA
https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html 

Do this in shell, not the python environment
